# Generated by Django 3.0.5 on 2021-05-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('cast', models.CharField(blank=True, max_length=600, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('listed_in', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
